use_frameworks!

platform :ios, '9.0'

target 'CLCDownload_Example' do
  pod 'CLCDownload', :path => '../'

  target 'CLCDownload_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
